version: "3.3"
services:
  api:
    # image: shaurcasm/webbook
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 5000
    ports:
      - "8080:5000"

  postgres:
    image: postgres:12.9  
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db